### ISSUE TITLE
Output Error

### ISSUE THREAD

**Issue by pbelmann** [metagenomics/MeRaGENE#146]
Sometimes the pipeline reports the following error:

~~~
Directory /home/belmann/projects/bioPipeline/tmp/output already exists. Please remove it or assign another output directory.
Exception in thread "Thread-2" java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at nextflow.Global.cleanUp(Global.groovy:163)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158)
        at nextflow.Global$__clinit__closure2.doCall(Global.groovy:178)
        at nextflow.Global$__clinit__closure2.doCall(Global.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:420)
        at groovy.lang.Closure.run(Closure.java:507)
        at java.lang.Thread.run(Thread.java:745)
~~~

instead of 

~~~
N E X T F L O W  ~  version 0.16.2
Pulling metagenomics/MeRaGENE ...
 Already-up-to-date
Launching 'metagenomics/MeRaGENE' - revision: 601f87534f [master]
[warm up] executor > local
Directory /home/belmann/projects/bioPipeline/tmp/output already exists. Please remove it or assign another output directory.
~~~

**Comment by pditommaso** [comment]
I think the problem is caused by the `exit` method that is not meant to be used inside a process. https://github.com/metagenomics/MeRaGENE/blob/master/main.nf#L41

Moving it outside the scope of the process or on top of your script should solve the problem.

**Comment by pbelmann** [comment]
thx @pditommaso
